/**
 * Writes mobile_app/.env with your PC's LAN IP for physical devices.
 * Usage: node scripts/write-api-env.js
 */
const fs = require("fs");
const os = require("os");
const path = require("path");

function getLanIpv4() {
  const nets = os.networkInterfaces();
  const candidates = [];

  for (const entries of Object.values(nets)) {
    for (const net of entries || []) {
      if (net.family !== "IPv4" || net.internal) continue;
      candidates.push(net.address);
    }
  }

  const preferred = candidates.find((ip) => ip.startsWith("192.168."));
  return preferred ?? candidates[0] ?? "127.0.0.1";
}

const port = process.env.EXPO_PUBLIC_API_PORT || "5000";
const ip = getLanIpv4();
const apiUrl = `http://${ip}:${port}/api`;
const envPath = path.join(__dirname, "..", ".env");

const header = `# Generated by npm run env:api — restart Expo after changes
# Use "auto" to derive host from Expo dev server instead:
# EXPO_PUBLIC_API_URL=auto
`;

const body = `EXPO_PUBLIC_API_URL=${apiUrl}
`;

fs.writeFileSync(envPath, header + body, "utf8");
console.log(`Wrote ${envPath}`);
console.log(`EXPO_PUBLIC_API_URL=${apiUrl}`);
console.log("Restart: npx expo start -c");
